export type ItemKind = "need" | "strength" | "binary";
export type DomainType = "core" | "module" | "placement" | "transition";

export interface CansItem {
  id: string;
  label: string;
  kind: ItemKind;
  opensModule?: string;
}

export interface CansDomain {
  id: string;
  title: string;
  shortTitle: string;
  type: DomainType;
  items: CansItem[];
}

export interface CansInstrument {
  id: "cans-0-5" | "cans-5-17";
  title: string;
  ageRange: string;
  version: string;
  source: string;
  domains: CansDomain[];
}

const item = (id: string, label: string, kind: ItemKind = "need", opensModule?: string): CansItem => ({
  id,
  label,
  kind,
  opensModule,
});

export const needAnchors = [
  "0 - Nessuna evidenza / nessuna azione",
  "1 - Monitorare, prevenire o osservare",
  "2 - Azione o intervento richiesto",
  "3 - Azione intensiva o immediata",
];

export const strengthAnchors = [
  "0 - Colonna portante",
  "1 - Presente e utile",
  "2 - Potenziale da potenziare",
  "3 - Non identificato",
];

export const binaryAnchors = ["No", "Si"];

const cans05Domains: CansDomain[] = [
  {
    id: "05-life",
    title: "Funzionamento nel contesto di vita",
    shortTitle: "Contesto",
    type: "core",
    items: [
      item("05-life-development", "Sviluppo", "need", "05-dev"),
      item("05-life-motor", "Sviluppo motorio", "need", "05-motor"),
      item("05-life-communication", "Comunicazione", "need", "05-communication"),
      item("05-life-regulation", "Regolazione", "need", "05-regulation"),
      item("05-life-medical", "Cure mediche e fisiche", "need", "05-medical"),
      item("05-life-child-caregiver", "Relazione bambino/caregiver"),
      item("05-life-attachment", "Attaccamento"),
      item("05-life-play", "Gioco"),
      item("05-life-family", "Famiglia"),
      item("05-life-living", "Contesto di vita"),
      item("05-life-daily", "Funzionamento quotidiano"),
      item("05-life-social", "Funzionamento sociale"),
      item("05-life-preschool", "Cure infantili prescolari", "need", "05-school"),
      item("05-life-acculturation", "Acculturazione", "need", "05-culture"),
    ],
  },
  {
    id: "05-risk-factors",
    title: "Fattori di rischio",
    shortTitle: "Rischi storici",
    type: "core",
    items: [
      item("05-risk-birth-weight", "Peso alla nascita"),
      item("05-risk-prenatal", "Cure prenatali"),
      item("05-risk-gestation", "Durata della gravidanza"),
      item("05-risk-labor", "Travaglio/parto"),
      item("05-risk-substance-exposure", "Esposizione a sostanze"),
      item("05-risk-family-problems", "Problemi genitori/fratelli"),
      item("05-risk-maternal", "Disponibilita materna"),
      item("05-risk-trauma-adjustment", "Adattamento al trauma", "need", "05-trauma"),
    ],
  },
  {
    id: "05-strengths",
    title: "Punti di forza dell'utente",
    shortTitle: "Punti di forza",
    type: "core",
    items: [
      item("05-str-family", "Famiglia come punto di forza", "strength"),
      item("05-str-interpersonal", "Capacita interpersonali", "strength"),
      item("05-str-stability", "Stabilita delle relazioni", "strength"),
      item("05-str-curiosity", "Curiosita", "strength"),
      item("05-str-perseverance", "Perseveranza", "strength"),
      item("05-str-solitary-play", "Gioco solitario", "strength"),
      item("05-str-play-with-others", "Gioco con altri", "strength"),
      item("05-str-creativity", "Creativita/immaginazione", "strength"),
      item("05-str-adaptability", "Adattabilita", "strength"),
    ],
  },
  {
    id: "05-caregiver",
    title: "Bisogni e risorse costanti del caregiver",
    shortTitle: "Caregiver",
    type: "core",
    items: [
      item("05-care-education", "Competenze normative/educative"),
      item("05-care-involvement", "Coinvolgimento nella cura"),
      item("05-care-knowledge", "Conoscenza/consapevolezza"),
      item("05-care-communicate", "Capacita di comunicare"),
      item("05-care-listen", "Capacita di ascolto"),
      item("05-care-empathy", "Empatia"),
      item("05-care-stress", "Stress familiare"),
      item("05-care-daily", "Cura di se/vita quotidiana"),
      item("05-care-organization", "Organizzazione"),
      item("05-care-social", "Risorse sociali"),
      item("05-care-physical", "Salute fisica"),
      item("05-care-mental", "Salute mentale"),
      item("05-care-substances", "Uso di sostanze"),
      item("05-care-developmental", "Sviluppo/bisogni evolutivi"),
      item("05-care-access", "Accessibilita ai servizi di cura infantili"),
      item("05-care-workschool", "Funzionamento lavorativo/scolastico"),
      item("05-care-goals", "Realizzazione obiettivi formativi"),
      item("05-care-legal", "Aspetti legali"),
      item("05-care-financial", "Risorse finanziarie"),
      item("05-care-transport", "Trasporti"),
      item("05-care-safety", "Sicurezza"),
      item("05-care-housing", "Stabilita abitativa"),
    ],
  },
  {
    id: "05-emotional",
    title: "Bisogni emotivo-comportamentali dell'utente",
    shortTitle: "Emotivo",
    type: "core",
    items: [
      item("05-emo-autism", "Spettro autistico"),
      item("05-emo-depression", "Depressione"),
      item("05-emo-anxiety", "Ansia"),
      item("05-emo-impulsivity", "Impulsivita"),
      item("05-emo-oppositional", "Oppositivita"),
      item("05-emo-anger", "Controllo della rabbia"),
      item("05-emo-attention", "Capacita di prestare attenzione"),
      item("05-emo-growth", "Ritardo nella crescita"),
      item("05-emo-hyper", "Iper-reattivita"),
      item("05-emo-atypical", "Comportamenti atipici"),
      item("05-emo-restricted", "Interessi ristretti"),
    ],
  },
  {
    id: "05-danger",
    title: "Comportamenti a rischio",
    shortTitle: "Rischio",
    type: "core",
    items: [
      item("05-danger-self-harm", "Autolesionismo"),
      item("05-danger-aggressive", "Comportamento aggressivo"),
      item("05-danger-social", "Comportamenti intenzionali socialmente disfunzionali"),
      item("05-danger-agreement", "Accordo su bisogni e punti di forza"),
      item("05-danger-coordination", "Coordinamento delle cure"),
    ],
  },
  {
    id: "05-dev",
    title: "Modulo: bisogni evolutivi/di sviluppo",
    shortTitle: "Sviluppo",
    type: "module",
    items: [
      item("05-dev-cognitive", "Livello cognitivo"),
      item("05-dev-socio", "Sviluppo socio-emotivo"),
      item("05-dev-selfcare", "Capacita cura di se e autonomie"),
    ],
  },
  {
    id: "05-motor",
    title: "Modulo: motorio",
    shortTitle: "Motorio",
    type: "module",
    items: [item("05-motor-gross", "Motricita globale"), item("05-motor-fine", "Motricita fine"), item("05-motor-coordination", "Coordinazione")],
  },
  {
    id: "05-communication",
    title: "Modulo: comunicazione",
    shortTitle: "Comunicazione",
    type: "module",
    items: [
      item("05-com-receptive", "Linguaggio recettivo"),
      item("05-com-aac", "Comunicazione aumentativa"),
      item("05-com-expressive", "Linguaggio espressivo"),
      item("05-com-articulation", "Articolazione del linguaggio"),
      item("05-com-gestures", "Gesti"),
      item("05-com-pragmatics", "Pragmatica del linguaggio"),
      item("05-com-stereotyped", "Produzioni verbali stereotipate"),
    ],
  },
  {
    id: "05-regulation",
    title: "Modulo: regolazione",
    shortTitle: "Regolazione",
    type: "module",
    items: [
      item("05-reg-feeding", "Difficolta di alimentazione/nutrizione"),
      item("05-reg-evacuation", "Evacuazione"),
      item("05-reg-sleep", "Sonno"),
      item("05-reg-emotion", "Controllo emotivo"),
      item("05-reg-selfstim", "Autostimolazione"),
      item("05-reg-sensory", "Responsivita sensoriale"),
    ],
  },
  {
    id: "05-medical",
    title: "Modulo: cure mediche e fisiche",
    shortTitle: "Medico",
    type: "module",
    items: [
      item("05-med-life", "Pericolo di vita"),
      item("05-med-chronic", "Cronicizzazione"),
      item("05-med-diagnostic", "Complessita diagnostica"),
      item("05-med-emotional", "Risposta emotiva"),
      item("05-med-impairment", "Compromissione del funzionamento"),
      item("05-med-adherence", "Coinvolgimento/adesione al trattamento"),
      item("05-med-intensity", "Intensita del trattamento"),
      item("05-med-organization", "Complessita organizzativa"),
    ],
  },
  {
    id: "05-school",
    title: "Modulo: scuola",
    shortTitle: "Scuola",
    type: "module",
    items: [
      item("05-school-behavior", "Comportamento"),
      item("05-school-attendance", "Frequenza"),
      item("05-school-teachers", "Relazione con gli insegnanti"),
      item("05-school-performance", "Rendimento"),
      item("05-school-compatibility", "Compatibilita"),
      item("05-school-peers", "Relazione con i pari"),
    ],
  },
  {
    id: "05-culture",
    title: "Modulo: integrazione culturale",
    shortTitle: "Cultura",
    type: "module",
    items: [
      item("05-cult-language-user", "Padronanza della lingua utente"),
      item("05-cult-identity-user", "Identita culturale utente"),
      item("05-cult-stress-user", "Stress culturale utente"),
      item("05-cult-rituals", "Rituali"),
      item("05-cult-congruence", "Congruenza culturale"),
      item("05-cult-language-caregiver", "Padronanza della lingua caregiver"),
      item("05-cult-identity-caregiver", "Identita culturale caregiver"),
      item("05-cult-distress", "Manifestazione di disagio"),
      item("05-cult-knowledge", "Congruenza nella conoscenza"),
      item("05-cult-help", "Congruenza nella richiesta di aiuto"),
    ],
  },
  {
    id: "05-trauma",
    title: "Modulo: trauma",
    shortTitle: "Trauma",
    type: "module",
    items: [
      item("05-trauma-affect", "Regolazione degli affetti"),
      item("05-trauma-reexperience", "Rivivere il trauma"),
      item("05-trauma-avoidance", "Evitamento"),
      item("05-trauma-hypervigilance", "Ipervigilanza"),
      item("05-trauma-numbing", "Indifferenza/insensibilita"),
      item("05-trauma-dissociation", "Dissociazione"),
      item("05-trauma-grief", "Angoscia traumatica"),
      item("05-ace-sexual", "Abuso sessuale", "binary"),
      item("05-ace-physical", "Abuso fisico", "binary"),
      item("05-ace-emotional", "Abuso emotivo", "binary"),
      item("05-ace-neglect", "Incuria/trascuratezza", "binary"),
      item("05-ace-medical", "Trauma medico", "binary"),
      item("05-ace-disaster", "Disastri naturali", "binary"),
      item("05-ace-domestic", "Testimone di violenza domestica", "binary"),
      item("05-ace-community", "Testimone di violenza nel contesto di vita", "binary"),
      item("05-ace-criminal", "Testimone/vittima di attivita criminali", "binary"),
      item("05-ace-attachment", "Interruzione accudimento/attaccamento", "binary"),
      item("05-ace-war", "Vittima di guerra/terrorismo", "binary"),
      item("05-ace-parent-crime", "Comportamento criminale dei genitori", "binary"),
      item("05-abuse-proximity", "Prossimita emotiva"),
      item("05-abuse-frequency", "Frequenza"),
      item("05-abuse-duration", "Durata"),
      item("05-abuse-violence", "Violenza fisica"),
      item("05-abuse-disclosure", "Reazione alla rivelazione"),
    ],
  },
  {
    id: "05-placement",
    title: "Modulo: collocamento",
    shortTitle: "Collocamento",
    type: "placement",
    items: [
      item("05-place-investment", "Investimento sul trattamento"),
      item("05-place-behavior", "Comportamenti"),
      item("05-place-home-visits", "Rientri a casa"),
      item("05-place-caregiver-involvement", "Coinvolgimento del caregiver"),
      item("05-place-interaction", "Interazione utente/caregiver"),
      item("05-place-progress", "Progressi raggiungimento obiettivi"),
      item("05-place-discharge", "Possibilita di dimissione"),
      item("05-current-education", "Caregiver attuale: competenze normative/educative"),
      item("05-current-involvement", "Caregiver attuale: coinvolgimento nella cura"),
      item("05-current-knowledge", "Caregiver attuale: conoscenza/consapevolezza"),
      item("05-current-organization", "Caregiver attuale: organizzazione"),
      item("05-current-social", "Caregiver attuale: risorse sociali"),
      item("05-current-physical", "Caregiver attuale: salute fisica"),
      item("05-current-stress", "Caregiver attuale: stress familiare"),
      item("05-current-collaboration", "Caregiver attuale: collaborazione con altri caregiver"),
    ],
  },
];

const cans517Domains: CansDomain[] = [
  {
    id: "517-life",
    title: "Funzionamento nel contesto di vita",
    shortTitle: "Contesto",
    type: "core",
    items: [
      item("517-life-family", "Famiglia"),
      item("517-life-living", "Contesto di vita"),
      item("517-life-sleep", "Sonno"),
      item("517-life-social", "Funzionamento sociale"),
      item("517-life-bullied", "Bullismo subito"),
      item("517-life-sexual-development", "Sviluppo/identita sessuale"),
      item("517-life-recreation", "Attivita ricreative/di svago"),
      item("517-life-development", "Sviluppo", "need", "517-dev"),
      item("517-life-communication", "Comunicazione", "need", "517-communication"),
      item("517-life-judgment", "Giudizio"),
      item("517-life-acculturation", "Acculturazione", "need", "517-culture"),
      item("517-life-legal", "Aspetti legali"),
      item("517-life-medical", "Cure mediche e fisiche", "need", "517-medical"),
      item("517-life-daily", "Funzionamento quotidiano"),
      item("517-life-independent", "Vita indipendente", "need", "517-independent"),
    ],
  },
  {
    id: "517-school",
    title: "Scuola",
    shortTitle: "Scuola",
    type: "core",
    items: [
      item("517-school-behavior", "Comportamento"),
      item("517-school-attendance", "Frequenza"),
      item("517-school-performance", "Rendimento"),
      item("517-school-learning", "Difficolta di apprendimento"),
      item("517-school-teachers", "Relazione con gli insegnanti"),
      item("517-school-peers", "Relazioni con i pari"),
    ],
  },
  {
    id: "517-strengths",
    title: "Punti di forza",
    shortTitle: "Punti di forza",
    type: "core",
    items: [
      item("517-str-family", "Famiglia come punto di forza", "strength"),
      item("517-str-interpersonal", "Capacita interpersonali", "strength"),
      item("517-str-optimism", "Ottimismo", "strength"),
      item("517-str-school", "Scuola come punto di forza", "strength"),
      item("517-str-attitudes", "Attitudini", "strength"),
      item("517-str-talents", "Talenti/interessi", "strength"),
      item("517-str-spiritual", "Aspetti spirituali/religiosi", "strength"),
      item("517-str-community", "Inserimento realta sociale", "strength"),
      item("517-str-relationship", "Stabilita delle relazioni", "strength"),
      item("517-str-involvement", "Coinvolgimento dell'utente", "strength"),
      item("517-str-natural", "Reti naturali", "strength"),
      item("517-str-curiosity", "Curiosita", "strength"),
      item("517-str-perseverance", "Perseveranza", "strength"),
      item("517-str-resilience", "Resilienza", "strength"),
      item("517-str-expression", "Espressione di se", "strength"),
    ],
  },
  {
    id: "517-caregiver",
    title: "Bisogni e risorse del caregiver",
    shortTitle: "Caregiver",
    type: "core",
    items: [
      item("517-care-education", "Competenze educative"),
      item("517-care-involvement", "Coinvolgimento nella cura"),
      item("517-care-knowledge", "Conoscenza/consapevolezza"),
      item("517-care-communicate", "Capacita di comunicare"),
      item("517-care-listen", "Capacita di ascolto"),
      item("517-care-organization", "Organizzazione"),
      item("517-care-social", "Risorse sociali"),
      item("517-care-housing", "Stabilita abitativa"),
      item("517-care-physical", "Salute fisica"),
      item("517-care-mental", "Salute mentale"),
      item("517-care-substances", "Uso di sostanze"),
      item("517-care-development", "Sviluppo/bisogni evolutivi"),
      item("517-care-access", "Accessibilita ai servizi di cura infantili"),
      item("517-care-stress", "Stress familiare"),
      item("517-care-daily", "Cura di se/vita quotidiana"),
      item("517-care-workschool", "Funzionamento lavorativo/scolastico"),
      item("517-care-goals", "Realizzazione obiettivi formativi"),
      item("517-care-legal", "Aspetti legali"),
      item("517-care-financial", "Risorse finanziarie"),
      item("517-care-transport", "Trasporti"),
      item("517-care-safety", "Sicurezza"),
    ],
  },
  {
    id: "517-emotional",
    title: "Bisogni emotivo-comportamentali",
    shortTitle: "Emotivo",
    type: "core",
    items: [
      item("517-emo-autism", "Spettro autistico"),
      item("517-emo-psychosis", "Psicosi"),
      item("517-emo-impulsivity", "Impulsivita"),
      item("517-emo-depression", "Depressione"),
      item("517-emo-mania", "Mania"),
      item("517-emo-anxiety", "Ansia"),
      item("517-emo-opposition", "Oppositivita"),
      item("517-emo-conduct", "Condotta"),
      item("517-emo-trauma-adjustment", "Difficolta di adattamento al trauma", "need", "517-trauma"),
      item("517-emo-anger", "Controllo della rabbia"),
      item("517-emo-substances", "Uso di sostanze", "need", "517-substances"),
      item("517-emo-eating", "Difficolta di nutrizione/alimentazione"),
      item("517-emo-somatization", "Somatizzazione"),
    ],
  },
  {
    id: "517-danger",
    title: "Comportamenti a rischio",
    shortTitle: "Rischio",
    type: "core",
    items: [
      item("517-danger-suicide", "Rischio suicidario"),
      item("517-danger-self-harm", "Comportamenti autolesivi"),
      item("517-danger-other-self", "Altri comportamenti pericolosi per se"),
      item("517-danger-others", "Pericolo per gli altri", "need", "517-violence"),
      item("517-danger-sexual-aggression", "Aggressioni sessuali"),
      item("517-danger-runaway", "Fuga", "need", "517-runaway"),
      item("517-danger-delinquency", "Comportamenti delinquenziali", "need", "517-justice"),
      item("517-danger-fire", "Piromania"),
      item("517-danger-social", "Comportamenti intenzionali socialmente disfunzionali"),
      item("517-danger-sexual-reactive", "Comportamento reattivo di tipo sessuale"),
      item("517-danger-bullying", "Bullismo"),
    ],
  },
  {
    id: "517-transition",
    title: "Eta di transizione (16-21 anni)",
    shortTitle: "Transizione",
    type: "transition",
    items: [
      item("517-tr-independent", "Vita indipendente", "need", "517-independent"),
      item("517-tr-parenting", "Ruolo genitoriale", "need", "517-parenting"),
      item("517-tr-work", "Funzionamento lavorativo", "need", "517-work"),
      item("517-tr-medication", "Aderenza farmaco"),
      item("517-tr-intimate", "Relazioni intime"),
      item("517-tr-interpersonal", "Difficolta relazionali/interpersonali"),
      item("517-tr-transport", "Trasporti"),
      item("517-tr-training", "Obiettivi formativi"),
      item("517-tr-agreement", "Accordo su bisogni e punti di forza"),
      item("517-tr-coordination", "Coordinamento delle cure"),
    ],
  },
  {
    id: "517-dev",
    title: "Modulo: bisogni evolutivi/di sviluppo",
    shortTitle: "Sviluppo",
    type: "module",
    items: [item("517-dev-cognitive", "Livello cognitivo"), item("517-dev-socio", "Sviluppo socio-emotivo"), item("517-dev-selfcare", "Capacita cura di se e autonomie")],
  },
  {
    id: "517-communication",
    title: "Modulo: comunicazione",
    shortTitle: "Comunicazione",
    type: "module",
    items: [item("517-com-aac", "Comunicazione aumentativa")],
  },
  {
    id: "517-culture",
    title: "Modulo: integrazione culturale",
    shortTitle: "Cultura",
    type: "module",
    items: [
      item("517-cult-language-user", "Padronanza della lingua utente"),
      item("517-cult-identity-user", "Identita culturale utente"),
      item("517-cult-stress", "Stress integrazione culturale"),
      item("517-cult-rituals", "Rituali"),
      item("517-cult-congruence", "Congruenza culturale"),
      item("517-cult-language-family", "Padronanza della lingua famiglia"),
      item("517-cult-identity-caregiver", "Identita culturale caregiver"),
      item("517-cult-distress", "Manifestazione di disagio"),
      item("517-cult-knowledge", "Congruenza nella conoscenza"),
      item("517-cult-help", "Congruenza richiesta aiuto"),
    ],
  },
  {
    id: "517-medical",
    title: "Modulo: cure mediche e fisiche",
    shortTitle: "Medico",
    type: "module",
    items: [
      item("517-med-life", "Pericolo di vita"),
      item("517-med-chronic", "Cronicizzazione"),
      item("517-med-diagnostic", "Complessita diagnostica"),
      item("517-med-emotional", "Risposta emotiva"),
      item("517-med-impairment", "Compromissione funzionamento"),
      item("517-med-involvement", "Coinvolgimento trattamento"),
      item("517-med-intensity", "Intensita trattamento"),
      item("517-med-organization", "Complessita organizzativa"),
      item("517-med-medication", "Aderenza farmaco"),
    ],
  },
  {
    id: "517-independent",
    title: "Modulo: vita indipendente",
    shortTitle: "Autonomie",
    type: "module",
    items: [
      item("517-ind-meals", "Preparazione dei pasti"),
      item("517-ind-shopping", "Shopping"),
      item("517-ind-cleaning", "Pulizie domestiche"),
      item("517-ind-money", "Gestione del denaro"),
      item("517-ind-devices", "Utilizzo dei dispositivi elettronici"),
      item("517-ind-housing", "Sicurezza abitativa"),
    ],
  },
  {
    id: "517-trauma",
    title: "Modulo: trauma",
    shortTitle: "Trauma",
    type: "module",
    items: [
      item("517-trauma-affect", "Regolazione affetti"),
      item("517-trauma-reexperience", "Rivivere il trauma"),
      item("517-trauma-dissociation", "Dissociazione"),
      item("517-trauma-avoidance", "Evitamento"),
      item("517-trauma-hyper", "Ipervigilanza/reattivita"),
      item("517-trauma-grief", "Angoscia traumatica"),
      item("517-trauma-numbing", "Insensibilita"),
      item("517-ace-sexual", "Abuso sessuale", "binary"),
      item("517-ace-physical", "Abuso fisico", "binary"),
      item("517-ace-emotional", "Abuso emotivo", "binary"),
      item("517-ace-neglect", "Incuria/trascuratezza", "binary"),
      item("517-ace-medical", "Trauma medico", "binary"),
      item("517-ace-disaster", "Disastri naturali", "binary"),
      item("517-ace-domestic", "Testimone di violenza domestica", "binary"),
      item("517-ace-community", "Testimone di violenza nel contesto di vita", "binary"),
      item("517-ace-criminal", "Testimone/vittima di attivita criminali", "binary"),
      item("517-ace-war", "Vittima di guerra/terrorismo", "binary"),
      item("517-ace-attachment", "Interruzione accudimento/attaccamento-perdite", "binary"),
      item("517-ace-parent-crime", "Comportamento criminale dei genitori", "binary"),
      item("517-abuse-proximity", "Prossimita emotiva"),
      item("517-abuse-frequency", "Frequenza"),
      item("517-abuse-duration", "Durata"),
      item("517-abuse-violence", "Violenza fisica"),
      item("517-abuse-disclosure", "Reazione alla rivelazione"),
    ],
  },
  {
    id: "517-substances",
    title: "Modulo: uso di sostanze",
    shortTitle: "Sostanze",
    type: "module",
    items: [
      item("517-sub-frequency", "Frequenza d'uso"),
      item("517-sub-duration", "Durata dell'uso"),
      item("517-sub-change", "Disposizione al cambiamento"),
      item("517-sub-recovery", "Ambiente di recupero"),
      item("517-sub-relapse", "Capacita di evitare la ricaduta"),
    ],
  },
  {
    id: "517-violence",
    title: "Modulo: bisogni correlati alla violenza",
    shortTitle: "Violenza",
    type: "module",
    items: [
      item("517-vio-physical-abuse", "Storia di abuso fisico"),
      item("517-vio-history", "Storia di violenza"),
      item("517-vio-domestic", "Testimone di violenza domestica"),
      item("517-vio-community", "Testimone di violenza nel contesto ambientale"),
      item("517-vio-frustration", "Gestione della frustrazione"),
      item("517-vio-hostility", "Ostilita"),
      item("517-vio-paranoid", "Pensiero paranoide"),
      item("517-vio-secondary", "Benefici secondari"),
      item("517-vio-ideation", "Ideazioni violente"),
      item("517-vio-awareness", "Consapevolezza"),
      item("517-vio-consequences", "Reazione alle conseguenze"),
      item("517-vio-selfcontrol", "Impegno nell'autocontrollo"),
      item("517-vio-intervention", "Coinvolgimento nell'intervento"),
    ],
  },
  {
    id: "517-runaway",
    title: "Modulo: fuga",
    shortTitle: "Fuga",
    type: "module",
    items: [
      item("517-run-frequency", "Frequenza della fuga"),
      item("517-run-duration", "Durata della fuga"),
      item("517-run-destination", "Coerenza della destinazione"),
      item("517-run-planning", "Pianificazione"),
      item("517-run-safety", "Sicurezza della destinazione"),
      item("517-run-illegal", "Coinvolgimento in attivita illegali"),
      item("517-run-return", "Probabilita di rientro"),
      item("517-run-others", "Coinvolgimento con altri"),
    ],
  },
  {
    id: "517-justice",
    title: "Modulo: bisogni giustizia minorile",
    shortTitle: "Giustizia",
    type: "module",
    items: [
      item("517-justice-offense", "Entita del reato"),
      item("517-justice-history", "Storia"),
      item("517-justice-reports", "Denunce"),
      item("517-justice-planning", "Pianificazione"),
      item("517-justice-community", "Sicurezza per la comunita"),
      item("517-justice-compliance", "Compliance legale"),
      item("517-justice-peers", "Influenza dei pari"),
      item("517-justice-parent-crime", "Comportamento criminale dei genitori"),
      item("517-justice-environment", "Influenze ambientali"),
    ],
  },
  {
    id: "517-parenting",
    title: "Modulo: ruolo di genitore/caregiver",
    shortTitle: "Ruolo CG",
    type: "module",
    items: [
      item("517-parent-education", "Competenze educative"),
      item("517-parent-involvement", "Coinvolgimento nella cura"),
      item("517-parent-knowledge", "Conoscenza/consapevolezza"),
      item("517-parent-organization", "Organizzazione"),
      item("517-parent-partner", "Relazione con il partner"),
    ],
  },
  {
    id: "517-work",
    title: "Modulo: lavoro",
    shortTitle: "Lavoro",
    type: "module",
    items: [
      item("517-work-aspirations", "Aspirazioni di carriera"),
      item("517-work-presence", "Presenza sul lavoro"),
      item("517-work-performance", "Prestazione lavorativa"),
      item("517-work-relationships", "Rapporti sul lavoro"),
    ],
  },
  {
    id: "517-placement",
    title: "Modulo: collocamento",
    shortTitle: "Collocamento",
    type: "placement",
    items: [
      item("517-place-investment", "Investimento sul collocamento e sul trattamento"),
      item("517-place-behavior", "Comportamenti"),
      item("517-place-home-visits", "Rientri a casa"),
      item("517-place-caregiver", "Coinvolgimento del caregiver"),
      item("517-place-interaction", "Interazione utente/caregiver"),
      item("517-place-progress", "Progressi raggiungimento obiettivi"),
      item("517-place-discharge", "Possibilita di dimissione"),
      item("517-current-education", "Caregiver attuale: competenze educative"),
      item("517-current-involvement", "Caregiver attuale: coinvolgimento nella cura"),
      item("517-current-knowledge", "Caregiver attuale: conoscenza/consapevolezza"),
      item("517-current-organization", "Caregiver attuale: organizzazione"),
      item("517-current-social", "Caregiver attuale: risorse sociali"),
      item("517-current-physical", "Caregiver attuale: salute fisica"),
      item("517-current-stress", "Caregiver attuale: stress familiare"),
      item("517-current-collaboration", "Caregiver attuale: collaborazione con altri caregiver"),
    ],
  },
];

export const instruments: CansInstrument[] = [
  {
    id: "cans-0-5",
    title: "CANS 0-5",
    ageRange: "0-5 anni",
    version: "Versione italiana 3.0, 2025",
    source: "Manuale CANS 0-5 Versione 3.0 2025",
    domains: cans05Domains,
  },
  {
    id: "cans-5-17",
    title: "CANS 5-17+",
    ageRange: "5-17+ anni; transizione 16-21",
    version: "Standard CANS Comprehensive 3.0, versione italiana 03.2026",
    source: "Manuale CANS 5-17+ versione 3.0_03.26",
    domains: cans517Domains,
  },
];

export const getInstrument = (id: CansInstrument["id"]) => instruments.find((instrument) => instrument.id === id) ?? instruments[0];
